version: '3'

networks:
  mlc_net:
    external:
      name: mlc_net

services:
  bdc:
    build: .
    container_name: bdc
    ports:
      - 8001:8000
    environment:
      - API_PUBLIC_URL=http://localhost:8000
      - API_INTERNAL_URL=http://api:8000
    networks:
      - mlc_net


